CREATE TABLE AREAS (
	AREAID INT PRIMARY KEY IDENTITY(1,1),
	AREACODE NVARCHAR(50) NOT NULL,
	AREANAME NVARCHAR(200) NOT NULL,
	AREADESCRIPTION NVARCHAR(250),
	ISACTIVE BIT NOT NULL DEFAULT 1,
	CREATEDATE DATETIME,
	CREATEBY NVARCHAR (100),
	MODIFYDATE DATETIME,
	MODIFYBY NVARCHAR(100)
)
GO
CREATE TABLE RACKS(
	RACKID INT PRIMARY KEY IDENTITY(1,1),
	AREAID INT NOT NULL FOREIGN KEY REFERENCES AREAS(AREAID),
	RACKCODE NVARCHAR(50) NOT NULL UNIQUE,
	RACKNAME NVARCHAR(200) NOT NULL,
	RACKDESCRIPTION NVARCHAR(255),
	CAPACITY INT NOT NULL CHECK (CAPACITY > 0),
	ISACTIVE BIT NOT NULL DEFAULT 1,
	CREATEDATE DATETIME,
	CREATEBY NVARCHAR (100),
	MODIFYDATE DATETIME,
	MODIFYBY NVARCHAR(100)
)
GO
CREATE TABLE STORAGES(
	STORAGEID INT PRIMARY KEY IDENTITY(1,1),
	BOOKS INT NOT NULL FOREIGN KEY REFERENCES BOOKS(BOOKID),
	RACKS INT NOT NULL FOREIGN KEY REFERENCES RACKS(RACKID),
)